name: Publish Package

on:
  push:
    branches: [main]
    paths:
      - "sdk/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        working-directory: ./sdk
        run: npm install

      - name: Build package
        working-directory: ./sdk
        run: npm run build

      - name: Publish to npm
        working-directory: ./sdk
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
